### ISSUE TITLE
Doesnot Works with ionic or Angular < 1.5.4

### ISSUE THREAD

**Issue by rizvanhaider** [talamaska/angular-radial-color-picker#8]
Knob of color picker does not works on angular  < 1.5.4

**Comment by rkunev** [comment]
Hi, @rizvanhaider . Sorry for not replying in time - it was Easter holidays in Bulgaria.

I'm already working on a bugfix for this issue. Turns out that prior to [angular 1.5.5](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#bug-fixes-19) the `$onChanges()` life-cycle hook is not called in some specific scenarios. Stay tuned for an update.

Edit: @talamaska A new Pull Request is created - #9
